# Default values for appscharts.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# This will set the replicaset count more information can be found here: https://kubernetes.io/docs/concepts/workloads/controllers/replicaset/
replicaCount: 1

# CP, Worker and Redis Images 
images:
  cp: public.ecr.aws/i9o0i2n0/demo-md-infra-cp:latest
  dp: public.ecr.aws/i9o0i2n0/demo-md-infra-dp:latest
  redis: redis

lables:
    app: demoapp

ports:
  cp: 3000
  redis: 6379

volumes:
  - name: db
    emptyDir: {}
